# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\kareg\PycharmProjects\Active_staff_motivation_qt\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_task_old(object):
    def setupUi(self, task_old):
        task_old.setObjectName("task_old")
        task_old.resize(632, 356)
        self.tasks_list = QtWidgets.QListWidget(task_old)
        self.tasks_list.setGeometry(QtCore.QRect(10, 50, 611, 301))
        self.tasks_list.setObjectName("tasks_list")
        self.filter = QtWidgets.QComboBox(task_old)
        self.filter.setGeometry(QtCore.QRect(130, 20, 171, 21))
        self.filter.setObjectName("filter")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter_button = QtWidgets.QPushButton(task_old)
        self.filter_button.setGeometry(QtCore.QRect(20, 20, 101, 23))
        self.filter_button.setObjectName("filter_button")
        self.task_old_close = QtWidgets.QPushButton(task_old)
        self.task_old_close.setGeometry(QtCore.QRect(540, 20, 75, 23))
        self.task_old_close.setObjectName("task_old_close")

        self.retranslateUi(task_old)
        QtCore.QMetaObject.connectSlotsByName(task_old)

    def retranslateUi(self, task_old):
        _translate = QtCore.QCoreApplication.translate
        task_old.setWindowTitle(_translate("task_old", "Выполненые задачи"))
        self.filter.setItemText(0, _translate("task_old", "ID по возрастанию"))
        self.filter.setItemText(1, _translate("task_old", "ID по убыванию"))
        self.filter.setItemText(2, _translate("task_old", "Название по возрастанию"))
        self.filter.setItemText(3, _translate("task_old", "Название по убыванию"))
        self.filter.setItemText(4, _translate("task_old", "Статус по возрастанию"))
        self.filter.setItemText(5, _translate("task_old", "Статус по убыванию"))
        self.filter.setItemText(6, _translate("task_old", "Группа по возрастанию"))
        self.filter.setItemText(7, _translate("task_old", "Группа по убыванию"))
        self.filter.setItemText(8, _translate("task_old", "Дата по возрастанию"))
        self.filter.setItemText(9, _translate("task_old", "Дата по убыванию"))
        self.filter_button.setText(_translate("task_old", "Фильтр"))
        self.task_old_close.setText(_translate("task_old", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    task_old = QtWidgets.QWidget()
    ui = Ui_task_old()
    ui.setupUi(task_old)
    task_old.show()
    sys.exit(app.exec_())
