# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\kareg\PycharmProjects\Active_staff_motivation_qt\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_New_task(object):
    def setupUi(self, New_task):
        New_task.setObjectName("New_task")
        New_task.resize(467, 289)
        self.label = QtWidgets.QLabel(New_task)
        self.label.setGeometry(QtCore.QRect(40, 20, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(New_task)
        self.label_2.setGeometry(QtCore.QRect(130, 70, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(New_task)
        self.label_3.setGeometry(QtCore.QRect(180, 20, 101, 16))
        self.label_3.setObjectName("label_3")
        self.lead_time = QtWidgets.QDateEdit(New_task)
        self.lead_time.setGeometry(QtCore.QRect(330, 200, 110, 22))
        self.lead_time.setTimeSpec(QtCore.Qt.LocalTime)
        self.lead_time.setObjectName("lead_time")
        self.label_5 = QtWidgets.QLabel(New_task)
        self.label_5.setGeometry(QtCore.QRect(340, 180, 91, 16))
        self.label_5.setObjectName("label_5")
        self.create_new_task = QtWidgets.QPushButton(New_task)
        self.create_new_task.setGeometry(QtCore.QRect(40, 240, 101, 31))
        self.create_new_task.setObjectName("create_new_task")
        self.label_4 = QtWidgets.QLabel(New_task)
        self.label_4.setGeometry(QtCore.QRect(310, 20, 81, 16))
        self.label_4.setObjectName("label_4")
        self.description_task = QtWidgets.QTextEdit(New_task)
        self.description_task.setGeometry(QtCore.QRect(40, 90, 271, 141))
        self.description_task.setObjectName("description_task")
        self.label_6 = QtWidgets.QLabel(New_task)
        self.label_6.setGeometry(QtCore.QRect(350, 100, 81, 16))
        self.label_6.setObjectName("label_6")
        self.ball = QtWidgets.QSpinBox(New_task)
        self.ball.setGeometry(QtCore.QRect(350, 120, 42, 22))
        self.ball.setMaximum(10)
        self.ball.setObjectName("ball")
        self.splitter = QtWidgets.QSplitter(New_task)
        self.splitter.setGeometry(QtCore.QRect(30, 40, 391, 20))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.name_task = QtWidgets.QLineEdit(self.splitter)
        self.name_task.setObjectName("name_task")
        self.status_task = QtWidgets.QComboBox(self.splitter)
        self.status_task.setObjectName("status_task")
        self.status_task.addItem("")
        self.status_task.addItem("")
        self.status_task.addItem("")
        self.status_task.addItem("")
        self.status_task.addItem("")
        self.status_task.addItem("")
        self.group_task = QtWidgets.QLineEdit(self.splitter)
        self.group_task.setObjectName("group_task")

        self.retranslateUi(New_task)
        QtCore.QMetaObject.connectSlotsByName(New_task)

    def retranslateUi(self, New_task):
        _translate = QtCore.QCoreApplication.translate
        New_task.setWindowTitle(_translate("New_task", "Новая задача"))
        self.label.setText(_translate("New_task", "Название задачи"))
        self.label_2.setText(_translate("New_task", "Описание задачи"))
        self.label_3.setText(_translate("New_task", "Статус задачи"))
        self.label_5.setText(_translate("New_task", "Срок выполнения до"))
        self.create_new_task.setText(_translate("New_task", "Создать"))
        self.label_4.setText(_translate("New_task", "Группа задачи"))
        self.label_6.setText(_translate("New_task", "Баллы"))
        self.status_task.setItemText(0, _translate("New_task", "Очень срочная"))
        self.status_task.setItemText(1, _translate("New_task", "Срочная"))
        self.status_task.setItemText(2, _translate("New_task", "Средняя срочность"))
        self.status_task.setItemText(3, _translate("New_task", "Обычная"))
        self.status_task.setItemText(4, _translate("New_task", "Не срочная"))
        self.status_task.setItemText(5, _translate("New_task", "Не обязательная"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    New_task = QtWidgets.QDialog()
    ui = Ui_New_task()
    ui.setupUi(New_task)
    New_task.show()
    sys.exit(app.exec_())
