# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\kareg\PycharmProjects\Active_staff_motivation_qt\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_New_task(object):
    def setupUi(self, New_task):
        New_task.setObjectName("New_task")
        New_task.resize(569, 321)
        self.label = QtWidgets.QLabel(New_task)
        self.label.setGeometry(QtCore.QRect(60, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(New_task)
        self.label_2.setGeometry(QtCore.QRect(140, 90, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(New_task)
        self.label_3.setGeometry(QtCore.QRect(220, 20, 101, 16))
        self.label_3.setObjectName("label_3")
        self.dateEdit = QtWidgets.QDateEdit(New_task)
        self.dateEdit.setGeometry(QtCore.QRect(360, 140, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label_5 = QtWidgets.QLabel(New_task)
        self.label_5.setGeometry(QtCore.QRect(360, 120, 91, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(New_task)
        self.pushButton.setGeometry(QtCore.QRect(70, 260, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(New_task)
        self.textBrowser.setGeometry(QtCore.QRect(30, 40, 121, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.comboBox = QtWidgets.QComboBox(New_task)
        self.comboBox.setGeometry(QtCore.QRect(210, 40, 111, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(New_task)
        self.comboBox_2.setGeometry(QtCore.QRect(380, 40, 111, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_4 = QtWidgets.QLabel(New_task)
        self.label_4.setGeometry(QtCore.QRect(400, 20, 81, 16))
        self.label_4.setObjectName("label_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(New_task)
        self.textBrowser_2.setGeometry(QtCore.QRect(30, 110, 291, 141))
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.retranslateUi(New_task)
        QtCore.QMetaObject.connectSlotsByName(New_task)

    def retranslateUi(self, New_task):
        _translate = QtCore.QCoreApplication.translate
        New_task.setWindowTitle(_translate("New_task", "Новая задача"))
        self.label.setText(_translate("New_task", "Название задачи"))
        self.label_2.setText(_translate("New_task", "Описание задачи"))
        self.label_3.setText(_translate("New_task", "Статус задачи"))
        self.label_5.setText(_translate("New_task", "Срок выполнения"))
        self.pushButton.setText(_translate("New_task", "Создать"))
        self.label_4.setText(_translate("New_task", "Группа задачи"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    New_task = QtWidgets.QDialog()
    ui = Ui_New_task()
    ui.setupUi(New_task)
    New_task.show()
    sys.exit(app.exec_())
