# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\kareg\PycharmProjects\Active_staff_motivation_qt\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_reg_one(object):
    def setupUi(self, win_reg_one):
        win_reg_one.setObjectName("win_reg_one")
        win_reg_one.resize(239, 215)
        win_reg_one.setMinimumSize(QtCore.QSize(239, 215))
        win_reg_one.setMaximumSize(QtCore.QSize(239, 215))
        self.layoutWidget = QtWidgets.QWidget(win_reg_one)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 200, 183))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.user_login = QtWidgets.QLineEdit(self.layoutWidget)
        self.user_login.setObjectName("user_login")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.user_login)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.user_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.user_password.setObjectName("user_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.user_password)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.first_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.first_name.setObjectName("first_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.first_name)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.second_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.second_name.setObjectName("second_name")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.second_name)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.patronymic = QtWidgets.QLineEdit(self.layoutWidget)
        self.patronymic.setObjectName("patronymic")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.patronymic)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.position = QtWidgets.QLineEdit(self.layoutWidget)
        self.position.setObjectName("position")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.position)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.formLayout)
        self.login_button = QtWidgets.QPushButton(self.layoutWidget)
        self.login_button.setObjectName("login_button")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.login_button)

        self.retranslateUi(win_reg_one)
        QtCore.QMetaObject.connectSlotsByName(win_reg_one)

    def retranslateUi(self, win_reg_one):
        _translate = QtCore.QCoreApplication.translate
        win_reg_one.setWindowTitle(_translate("win_reg_one", "Регистрация"))
        self.label.setText(_translate("win_reg_one", "Логин"))
        self.label_2.setText(_translate("win_reg_one", "Пароль"))
        self.label_4.setText(_translate("win_reg_one", "Имя"))
        self.label_3.setText(_translate("win_reg_one", "Фамилия"))
        self.label_5.setText(_translate("win_reg_one", "Отчество"))
        self.label_6.setText(_translate("win_reg_one", "Должность"))
        self.login_button.setText(_translate("win_reg_one", "Зарегистрироватся"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_reg_one = QtWidgets.QWidget()
    ui = Ui_win_reg_one()
    ui.setupUi(win_reg_one)
    win_reg_one.show()
    sys.exit(app.exec_())
