# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\kareg\PycharmProjects\Active_staff_motivation_qt\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(801, 472)
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.completed_task = QtWidgets.QListView(self.centralwidget)
        self.completed_task.setGeometry(QtCore.QRect(30, 40, 131, 261))
        self.completed_task.setObjectName("completed_task")
        self.tasks_in_progress = QtWidgets.QListView(self.centralwidget)
        self.tasks_in_progress.setGeometry(QtCore.QRect(240, 40, 191, 261))
        self.tasks_in_progress.setObjectName("tasks_in_progress")
        self.new_tasks = QtWidgets.QListView(self.centralwidget)
        self.new_tasks.setGeometry(QtCore.QRect(170, 40, 61, 261))
        self.new_tasks.setObjectName("new_tasks")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 121, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 20, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 20, 81, 16))
        self.label_3.setObjectName("label_3")
        self.user_data = QtWidgets.QLabel(self.centralwidget)
        self.user_data.setGeometry(QtCore.QRect(70, 390, 91, 16))
        self.user_data.setObjectName("user_data")
        self.registration_window = QtWidgets.QPushButton(self.centralwidget)
        self.registration_window.setEnabled(True)
        self.registration_window.setGeometry(QtCore.QRect(70, 420, 75, 23))
        self.registration_window.setMouseTracking(True)
        self.registration_window.setObjectName("registration_window")
        self.money = QtWidgets.QLabel(self.centralwidget)
        self.money.setGeometry(QtCore.QRect(250, 410, 61, 31))
        self.money.setObjectName("money")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(250, 390, 71, 16))
        self.label_8.setObjectName("label_8")
        self.progressBar_raise = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_raise.setGeometry(QtCore.QRect(430, 410, 321, 21))
        self.progressBar_raise.setProperty("value", 0)
        self.progressBar_raise.setObjectName("progressBar_raise")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(510, 380, 151, 21))
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 310, 131, 41))
        self.pushButton.setObjectName("pushButton")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(460, 50, 312, 183))
        self.calendarWidget.setObjectName("calendarWidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(580, 250, 71, 16))
        self.label_4.setObjectName("label_4")
        self.tasks_in_progress_2 = QtWidgets.QListView(self.centralwidget)
        self.tasks_in_progress_2.setGeometry(QtCore.QRect(530, 270, 151, 91))
        self.tasks_in_progress_2.setObjectName("tasks_in_progress_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(170, 320, 191, 21))
        self.comboBox.setObjectName("comboBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Список задач"))
        self.label_2.setText(_translate("MainWindow", "Описание задачи"))
        self.label_3.setText(_translate("MainWindow", "Статус задачи"))
        self.user_data.setText(_translate("MainWindow", "ФИО"))
        self.registration_window.setText(_translate("MainWindow", "Вход"))
        self.money.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Баллы"))
        self.label_10.setText(_translate("MainWindow", "Прогресс выполнения задач"))
        self.pushButton.setText(_translate("MainWindow", "Новая задача"))
        self.label_4.setText(_translate("MainWindow", "Срочные"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
